- name: Collection Check
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Verify controller collection version
      debug:
        msg: "Collection is available!"
      delegate_to: localhost
      # This will fail if the collection is missing
      collections:
        - ansible.controller
